### ISSUE TITLE
why authenticate function are in #ifdef __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ 

### ISSUE THREAD

**Issue by jeffssss** [tumblr/TMTumblrSDK#106]
I try to use `- (void)authenticate:(NSString *)URLScheme callback:(void(^)(NSError *))error;` and `- (BOOL)handleOpenURL:(NSURL *)url;` but xcode shows errors.

Finally I find out that `#ifdef __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__` in `TMAPIClient.h` and other files.

I've search a lot in Stackoverflow or Google or some thing but I still confused about why these two functions are in `#ifdef __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__`. And I want to know why `#ifdef __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__` is needed ?

Thanks a lot.

**Comment by jeffssss** [comment]
it seems that `#ifdef __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__` is used to make sure you are in mac os and not in iOS environment.

is it right?

**Comment by paulrehkugler** [comment]
What errors are you seeing?

**Comment by jeffssss** [comment]
I cannot use `- (void)authenticate:(NSString *)URLScheme callback:(void(^)(NSError *))error;` function when I develope my iOS Application.

And I solve this problem by learning from [this fork](https://github.com/felixmo/TMTumblrSDK/)

Thank you!
