### ISSUE TITLE
Is there any swift version ?

### ISSUE THREAD

**Issue by Mahadev77** [tumblr/TMTumblrSDK#119]

**Comment by paulrehkugler** [comment]
No, there is no version of the TMTumblrSDK that is written in Swift. However, the current SDK is just as interoperable with Swift as any other Objective-C framework.

**Comment by mattbischoff** [comment]
Would nullability annotations and generics support add any value?

**Comment by paulrehkugler** [comment]
Yup, they certainly would. This is the first time we've been asked about Swift support, but if there's a strong community need for better compatibility, we'll look into adding it.

Of course, we also welcome contributions to that affect. 😀
