### ISSUE TITLE
 "The operation couldn’t be completed. (Authentication request failed error 400.)"

### ISSUE THREAD

**Issue by KONGFANJI** [tumblr/TMTumblrSDK#121]
When I login in with emai and password ,it return an error with  "The operation couldn’t be completed. (Authentication request failed error 400.)" .The following code :   
 [TMAPIClient sharedInstance].OAuthConsumerKey = KOAuthConsumerKey;
    [TMAPIClient sharedInstance].OAuthConsumerSecret = KOAuthConsumerSecret;
//    [TMAPIClient sharedInstance].OAuthToken = KOAuthToken;
//    [TMAPIClient sharedInstance].OAuthTokenSecret = KOAuthTokenSecret;
    
    [[TMTumblrAuthenticator sharedInstance] xAuth:@"......@qq.com" password:@"......" callback:^(NSString *ad, NSString *dd, NSError *er) {
        if (er) {
            FJLog(@"%@",er);
        }
    }];

**Comment by jaydeep0004** [comment]
@KONGFANJI  is issue fixed? 
as i am getting same error.
