### ISSUE TITLE
No visible @interface for TMAPIClient declares the selector 'handleOpenURL:'

### ISSUE THREAD

**Issue by canpoyrazoglu** [tumblr/TMTumblrSDK#128]
I'm trying to follow the tutorial to use the SDK.

I'm following the steps, installed the SDK via pods, imported the header <TMTumblrSDK/TMAPIClient.h>.

When I try to insert the URL handling code:

`    return [[TMAPIClient sharedInstance] handleOpenURL:url];`

I'm getting an error indicating the interface doesn't declare the method.

What am I doing wrong?

I'm on latest iOS SDK + Xcode 8.3.

**Comment by canpoyrazoglu** [comment]
I see the method is encapsulated in an `#ifdef __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__` directive along with authentication method too. I'm sure those methods are to be called from an iOS app too (it has references to `UIApplicationDelegate` which is only available on iOS).

What am I doing wrong?

**Comment by paulrehkugler** [comment]
The method is encapsulated in [`#ifdef __ENVIRONMENT_IPHONE_OS_VERSION_MIN_REQUIRED__`](https://github.com/tumblr/TMTumblrSDK/blob/master/TMTumblrSDK/APIClient/TMAPIClient.h#L135), which makes it available only on iOS platforms. I recommend checking your build settings to ensure you’re building an iOS target.

**Comment by canpoyrazoglu** [comment]
Hello @paulrehkugler 

I am building for an iOS target. I've installed the SDK using Pods and there are 30+ other pods working perfectly.

The method is encapsulated in `#ifdef __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__` in my header, which I got from the `pod 'TMTumblrSDK'`. I haven't touched anything.

**Comment by pourhadi** [comment]
i am having the same issue
<img width="543" alt="screen shot 2017-05-04 at 2 55 49 pm" src="https://cloud.githubusercontent.com/assets/1731121/25722422/c982b1f0-30d9-11e7-9232-91629d2ed063.png">

**Comment by rofreg** [comment]
It appears that the latest release of the TMTumblrSDK pod is out of date – iOS-based authentication was merged in in [August 2016](https://github.com/tumblr/TMTumblrSDK/pull/112), but the latest release of the pod (v4.0.4) came out in [March 2016](https://github.com/tumblr/TMTumblrSDK/releases/tag/4.0.4). Could someone on the Tumblr team package up a new release?

In the meantime, you can get the latest version of TMTumblrSDK by pointing your Podfile directly at the master branch of this repo:
```
pod 'TMTumblrSDK', git: 'https://github.com/tumblr/TMTumblrSDK.git'
```
Once you've done that, you should be able to call `handleOpenURL` on iOS.

**Comment by paulrehkugler** [comment]
Version 4.0.5 resolves this issue.
