### ISSUE TITLE
Cannot upload a photo on device

### ISSUE THREAD

**Issue by Kelvin-Hu** [tumblr/TMTumblrSDK#65]
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  
  [TMAPIClient sharedInstance].OAuthConsumerKey = @".....";
  [TMAPIClient sharedInstance].OAuthConsumerSecret = @".....";
  
  return YES;
  }

-(void)postPhoto { 
    [[TMAPIClient sharedInstance] authenticate:@"photopostexample" callback:^(NSError *error) {
        if (error)
            NSLog(@"Authentication failed: %@ %@", error, [error description]);
        else {
            NSLog(@"Authentication successful!");

```
        [[TMAPIClient sharedInstance] photo:@"kelvinhu.tumblr.com"
                              filePathArray:@[[[NSBundle mainBundle] pathForResource:@"blue" ofType:@"png"]]
                           contentTypeArray:@[@"image/png"]
                              fileNameArray:@[@"blue.png"]
                                 parameters:@{@"caption" : @"Caption"}
                                   callback:^(id response, NSError *error) {
                                       if (error)
                                           NSLog(@"Error posting to Tumblr");
                                       else
                                           NSLog(@"Posted to Tumblr");
                                   }];
    }
}];
```

}

this code can run on the simulator successfully. but when I run it on the device, the error code 400 was showed, and cannot upload the photo.
Waiting for the answer.Thanks a lot.

**Comment by ykws** [comment]
Now simulator has a same error.
