### ISSUE TITLE
Problem while trying to login with webview authenticate: webView: callback:

### ISSUE THREAD

**Issue by soufianeEssabbane** [tumblr/TMTumblrSDK#67]
Hi, can anyone please explain to me what is the problem ?I Do clean the cache but nothing ...

Error Domain=NSURLErrorDomain Code=-1012 "The operation couldn’t be completed. (NSURLErrorDomain error -1012.)" UserInfo=0x18807a90 {NSErrorFailingURLKey=http://www.tumblr.com/oauth/request_token?oauth_callback=tumblrauthbeapping%3A%2F%2Ftumblr-authorize, NSErrorFailingURLStringKey=http://www.tumblr.com/oauth/request_token?oauth_callback=tumblrauthbeapping%3A%2F%2Ftumblr-authorize, NSUnderlyingError=0x18807ae0 "The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1012.)"}

**Comment by calsmith** [comment]
Has there been any progress with this? I have requested xAuth twice and even linked to this thread but have heard nothing...

**Comment by irace** [comment]
> Has there been any progress with this? I have requested xAuth twice (after being recommended by support to use oauth) and even linked to this thread but have heard nothing back since...

No, there hasn’t been. I’m going to add support for in-app web view authentication (similar to [this pull request](https://github.com/tumblr/TMTumblrSDK/pull/64)), begrudgingly. Not happy about this at all but xAuth has its own security concerns and we can’t rely on Apple changing their policies anytime soon.

We still have hopes of providing a better native solution, but for now this will have to do. I don’t have a timeframe for releasing a `TMTumblrSDK` update yet, but web view support will be in the next one that we do. In the meantime, please refer to the aforementioned pull request or roll something similar yourself if you have specific needs.
