### ISSUE TITLE
I am getting error when authenticating on iPhone 5, 5S

### ISSUE THREAD

**Issue by quycaoquoc** [tumblr/TMTumblrSDK#74]
Following is the code snippet that I tried:

[TMAPIClient sharedInstance].OAuthConsumerKey = @"<my consumer key>";
[TMAPIClient sharedInstance].OAuthConsumerSecret = @"<my consumer secret>";
    
[[TMAPIClient sharedInstance] authenticate:@"<my URLScheme>" callback:^(NSError *error) {
      if (error)
          NSLog(@"%@", error.description);
}];

Safari is not showing to allow user logging in. Instead, It always returns an error:

Error Domain=NSURLErrorDomain Code=-1012 "The operation couldn’t be completed. (NSURLErrorDomain error -1012.)" UserInfo=0x16d7af40 {NSErrorFailingURLKey=http://www.tumblr.com/oauth/request_token?oauth_callback=<my URLScheme>%3A%2F%2Ftumblr-authorize, NSErrorFailingURLStringKey=http://www.tumblr.com/oauth/request_token?oauth_callback=<my URLScheme>%3A%2F%2Ftumblr-authorize, NSUnderlyingError=0x16d85220 "The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1012.)"}

I have tested with 2 ways integrating (via Pods and Manually), but getting error on both.

It works in the passed, but I have no idea why it doesn't work anymore now, because I changed nothing.

It works on Simulator and other devices so far.

Please advise.

**Comment by irace** [comment]
Closing because I'm unable to debug this without more information.
