### ISSUE TITLE
Reblog issue (error 401)

### ISSUE THREAD

**Issue by martynovskij** [tumblr/TMTumblrSDK#78]
```
NSDictionary *params = @{
                         @"id" : 999999999999,
                         @"reblog_key": @"XXXXXX",
                         @"comment" : @"test comment",
                         };


[[TMAPIClient sharedInstance] reblogPost:@"test.tumblr.com"
                              parameters:params
                                callback:^(id response, NSError *error) {
```

...

response:
{
    meta =     {
        msg = "Not Authorized";
        status = 401;
    };
    response =     (
    );
}

OAuthConsumerKey, OAuthConsumerSecret, OAuthToken, OAuthTokenSecret is set correctly.

**Comment by mital87** [comment]
[[TMAPIClient sharedInstance] userInfo: ^(id result, NSError* error) {

         NSString * baseHostname = [result[@"user"][@"blogs"][0][@"url"] // first blog     
                                   stringByReplacingOccurrencesOfString:@"http:" withString:@""];
         baseHostname = [baseHostname stringByReplacingOccurrencesOfString:@"/" withString:@""];

     [[TMAPIClient sharedInstance] reblogPost: baseHostname  // @"loggedUser.tumblr.com"
                       parameters: params
                         callback: ^(id response, NSError * error) {
        ...
     }];
}];
