### ISSUE TITLE
No visible @interface ... declares selector "handleOpenURL"

### ISSUE THREAD

**Issue by r3mus** [tumblr/TMTumblrSDK#88]
I have no idea why, but using Xcode 6.2 this compiled fine; now it doesn't in Xcode 6.3:

```
#import "TMAPIClient.h"
// ...
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
    [[TMAPIClient sharedInstance] handleOpenURL:url];
}
```

I tried a clean, deleting derived data, and I even tried with `<TMTumblrSDK/TMAPIClient.h>` but no dice? 
Via CocoaPods, I'm `Using TMTumblrSDK (2.1.1)`

**Comment by mattbischoff** [comment]
Try `#import <TMTumblrSDK/TMAPIClient.h>`

**Comment by r3mus** [comment]
Yeah ^ I did try that too, no luck.

**Comment by r3mus** [comment]
Oh, I just realized it's inside the conditional

    #ifdef __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__

**Comment by r3mus** [comment]
Ah, just read https://github.com/tumblr/TMTumblrSDK/commit/c4fb542710d4d7d931e390c3755784ee4f151cf3. I'll try the fork - I implemented my own UIWebView, so hopefully it ties in with the fork nicely.
