### ISSUE TITLE
Whoops - JXHTTP is gone.

### ISSUE THREAD

**Issue by staykids** [tumblr/TMTumblrSDK#90]
By way of a failed "pod install" this morning, it looks the `jstn/JXHTTP` dependency has vanished (https://github.com/jstn/JXHTTP) so this framework needs to be updated to build properly.

**Comment by irace** [comment]
Yikes. I’ve pointed the `JXHTTP` pod at our Tumblr fork, so this is now working again. Thanks for flagging it up!
