### ISSUE TITLE
xauth failed. Error code 400.

### ISSUE THREAD

**Issue by mh4u** [tumblr/TMTumblrSDK#95]
When I xauth,I always get error(code 400) in callback block. Here is my code:
    [TMAPIClient sharedInstance].OAuthConsumerKey = @"KzKNocy4NqAYiIK..........";
    [TMAPIClient sharedInstance].OAuthConsumerSecret = @"NDxQ3s1Nz9........";
    [[TMAPIClient sharedInstance] xAuth:@".....@gmail.com" password:@"....." callback:^(NSError *error) {
        NSLog(@"%@", error);
    }];
I can't find where the problem is. Help!

**Comment by ArsalanReal** [comment]
I am also getting Error code 400 . Please help me in this.
[[TMAPIClient sharedInstance] xAuth:@".....@gmail.com" password:@"....." callback:^(NSError *error) {
NSLog(@"%@", error);
}];

**Comment by hassanizhar** [comment]
Me too getting the same error

**Comment by irace** [comment]
Have you gotten xAuth permission for your consumer key? xAuth access is not granted by default.

**Comment by ArsalanReal** [comment]
No. Don't know from where to do it. 

Please provide detail steps for it. Because no proper detail documentation for tumblr iOS is available or share simple iOS authentication example.

**Comment by irace** [comment]
https://github.com/tumblr/TMTumblrSDK#xauth

**Comment by fxpage** [comment]
Hi @irace , I have registered my application here : https://www.tumblr.com/oauth/apps
but still receiving 400 error.
Please let me know what should I do here.

Thanks,
Felix

**Comment by fxpage** [comment]
Oh, I found it.
There are buttons with text only, so I was not able to realize they are buttons.

Show secret key    Request xAuth   Explore API

Thanks

**Comment by KONGFANJI** [comment]
How do you solve this problem？

**Comment by naldikt** [comment]
As of this writing I don't think Tumblr support XAuth anymore.  The link fxpage mentioned doesn't have "Request xAuth" link nor there's any mention of it anywhere on tumblr developer page.

What I ended up doing is to utilize login part using https://github.com/OAuthSwift/OAuthSwift v1.1.2  , then set [TMAPIClient sharedInstance].OAuthConsumerKey, OAuthConsumerSecret, OAuthToken, OAuthTokenSecret on its successful login.  Things work again now.
